module.exports = {
    VIEW_TICKET: "viewTicket/id:",
    CREATE_TICKET_TEMPLATE_ID: 8,
    ASSIGNEE_TICKET_TEMPLATE_ID: 11,
    OVERDUE_TICKET_TEMPLATE_ID: 13,
    CLOSE_TICKET_TEMPLATE_ID:14,
    // LARK_APP_ID: 'cli_9f52131716bf1009',//PAWAN
    // LARK_APP_SECRET: "HA4jIElRMHTEKTlozm3UDfGS3Fnp1pBn",//PAWAN
    // LARK_APP_ID: 'cli_a0886ee4223d500a',
    // LARK_APP_SECRET: "5SBBS2eJ8VAjCBv0JlaQigWDTuhIgMJT",
    OFFICE_TYPE_ID: "C-6881958840925945861",
    DESIGNATION: "C-6881958840925962245",
    HELPDESK_ROLE: "C-6901548487595278341",
    DEV_HELPDESKROLE:"C-7023307315180748805",
    DEV_OFFICE_TYPE:"C-7022221507623403526",
    SLA_PLAN_24: "24",
    SLA_PLAN_48: "48",
    SLA_PLAN_96: "96",
    SLA_PLAN_1: "1",
    SLA_PLAN_30M: "30",
    SLA_PLAN_1DAY:"1 Day",
    SLA_PLAN_2DAY:"2 Day",
    SLA_PLAN_3DAY:"3 Day",
    SLA_PLAN_4DAY:"4 Day",
    SLA_PLAN_5DAY:"5 Day",
    SLA_PLAN_6DAY:"6 Day",
    SLA_PLAN_7DAY:"7 Day",
    SLA_PLAN_8DAY:"8 Day",
    SLA_PLAN_9DAY:"9 Day",
    SLA_PLAN_10DAY:"10 Day",
    SLA_PLAN_11DAY:"11 Day",
    SLA_PLAN_12DAY:"12 Day",
    SLA_PLAN_13DAY:"13 Day",
    SLA_PLAN_14DAY:"14 Day",
    SLA_PLAN_15DAY:"15 Day",
    SLA_PLAN_16DAY:"16 Day",
    SLA_PLAN_17DAY:"17 Day",
    SLA_PLAN_18DAY:"18 Day",
    SLA_PLAN_19DAY:"19 Day",
    SLA_PLAN_20DAY:"20 Day",
    SLA_PLAN_21DAY:"21 Day",
    SLA_PLAN_22DAY:"22 Day",
    SLA_PLAN_23DAY:"23 Day",
    SLA_PLAN_24DAY:"24 Day",
    SLA_PLAN_25DAY:"25 Day",
    SLA_PLAN_26DAY:"26 Day",
    SLA_PLAN_27DAY:"27 Day",
    SLA_PLAN_28DAY:"28 Day",
    SLA_PLAN_29DAY:"29 Day",
    SLA_PLAN_30DAY:"30 Day",
    CLOSE_TICKET: "feedbackForm",
    baseUrl: process.env.BASE_URL,
    COLLEGE_TYPES: ["college", "colleges", "nspira-c","rnet-colleges","nspira-cc","narius-cc","nspira-civils","jr colleges","coaching centre","cc"],
    SCHOOL_TYPES: ["school", "schools", "nspira-s","rnet-schools","srnet-schools"],
    ADMIN_TYPES: ["nspira-co","rnet","nspira-cc-co", "nspira-zo", "zonal office", "nguide-ro", "nguide", "cbd", "central office", "co", "nspira-press", "nspira-wh", "nguide-co", "nspira-campaigning", "campaigning", "civil services","printing press"],
    CHANGED_ASSIGNEE_TEMPLATE: "Assigned Ticket to",
    CHANGED_STATUS_TEMPLATE: "Changed Status to",
    TICKET_ESCALATED_TEMPLATE: "Escalated Ticket To",
    TICKET_FILE_UPLOAD: "ticket",
    S3_FILE_URL_ACTIVE_TIME: 60 * 5, //5 minutes
    lbl_ORIGINAL_MESSAGE:"Original Message",
    lbl_LAST_MESSAGE:"Last Message",
    lbl_FULL_MESSAGE:"Full Message",
    lbl_CLOSING_EMAIL_MESSAGE:"Closing email",

    //TicketReplies Labels
    lbl_CREATE_TICKET:"<p>Created&nbsp;by <strong>%{fullName} </strong></p>",
    lbl_CREATE_TICKET_ON_BEHALF:"<p>Created&nbsp;by <strong>%{fullName} </strong> onbehalf of <strong>%{behalfPersonName} </strong> </p>",
    lbl_ESCALATE_TICKET:"<p><strong>System </strong>escalated this to <strong>%{fullName}</strong> %{level}<strong> </strong></p>",
    lbl_ASSIGN_TICKET:"<p><strong>%{fullName} </strong>assigned this to <strong>%{assigneeName} </strong></p>",
    lbl_REOPEN_TICKET:"<p><strong>%{fullName} </strong>reopened ticket</p>",
    lbl_SUBCATEGORY_CHANGE_TICKET:"<p><strong>%{fullName} </strong>changed ticket SubCategory to <strong>%{categoryName}</strong></p>",
    lbl_CHANGE_STATUS_TICKET:"<p><strong>%{fullName} </strong>changed ticket status to <strong>%{statusName}</strong></p>",
    lbl_TRANSFER_TICKET:"<p><strong>%{fullName}, %{previousDepartmentName} </strong>initiated ticket transfer to <strong>%{departmentName} </strong></p>",
    lbl_TRANSFER_REASON:"<p><strong>Transfer Reason: </strong> %{reason}</p>",
    lbl_TRANSFER_TICKET_1:"<p><strong>%{fullName}, %{departmentName} </strong>initiated ticket transfer</p>",
    lbl_INTER_DEPARTMENT_ASSIGN_TICKET:"<p><strong>%{fullName} </strong>assigned ticket to <strong>%{assigneeName},%{departmentName}</strong></p>",
    lbl_INTER_DEPARTMENT_ASSIGN_TICKET_1:"<p><strong>%{fullName} </strong>assigned ticket to <strong>%{helpTopicName}, %{departmentName}</strong> from <strong>%{oldHelpTopicName}, %{oldDepartmentName}</strong> </p>",
    lbl_INTER_DEPARTMENT_ASSIGN_TICKET_2:"<p><strong>%{fullName} </strong>assigned ticket to <strong>%{departmentName}</strong> from <strong>%{oldDepartmentName}</strong> </p>",
    lbl_SATISFIED_TICKET:"<p><strong>%{fullName} </strong>mentioned Ticket Satisfaction as <strong>%{satisfaction}&nbsp;</strong></p>",
    lbl_NOT_SATISFIED_TICKET:"<p><strong>%{fullName} </strong>mentioned Ticket Satisfaction as <strong>%{satisfaction}. </strong><strong>Reason: </strong> %{reason}</p>",
    lbl_TRANSFER_BACK_TICKET:"<p><strong>%{fullName} </strong>transfer back this to <strong>%{departmentName} </strong></p>",
    lbl_CHANGE_SLA_PLAN_TICKET:"<p><strong>%{fullName} </strong>changed SLA plan to <strong>%{SLAPlan}</strong></p>",
    //End
    //Lark AlertType constants
    lbl_ALERT_TYPE_OPENED:"Opened",
    lbl_ALERT_TYPE_STATUS_CHANGED:"StatusChanged",
    lbl_ALERT_TYPE_CLOSED:"Closed",
    lbl_ALERT_TYPE_REOPENED:"Reopen",
    lbl_ALERT_TYPE_ASSIGNED:"Assigned",
    lbl_ALERT_TYPE_ESCALATED:"Escalated",
    lbl_ALERT_TYPE_TRANSFER_REQUEST:"Transfer Request",
    lbl_ALERT_TYPE_OVERDUE:"Overdue",
    lbl_HELPDESK_EMAIL:"helpdesk@narayanagroup.com",

    //Lark Alert Types colors
    lbl_ALERT_TYPE_COLOR_OPENED:"Blue",
    lbl_ALERT_TYPE_COLOR_STATUS_CHANGED:"Orange",
    lbl_ALERT_TYPE_COLOR_CLOSED:"Green",
    lbl_ALERT_TYPE_COLOR_REOPENED:"Grey",
    lbl_ALERT_TYPE_COLOR_ASSIGNED:"Blue",
    lbl_ALERT_TYPE_COLOR_ESCALATED:"Red",
    lbl_ALERT_TYPE_COLOR_TRANSFER_REQUEST:"Blue",
    lbl_ALERT_TYPE_COLOR_OVERDUE:"Red",

};