module.exports = {
    EMAIL_MANDATORY_ERROR:"Email is mandatory",
    PASSWORD_MANDATORY_ERROR:"Password is mandatory",
    FIRST_NAME_MANDATORY_ERROR:"FirstName is mandatory",
    LAST_NAME_MANDATORY_ERROR:"LastName is mandatory",
    TENANT_NAME_MANDATORY_ERROR:"Tenant name is mandatory",
    OTP_MANDATORY_ERROR:"OTP is mandatory",
    TENANT_ID_ERROR:"Tenant Id is mandatory",
    SOME_ERROR_OCCURRED:"Some error occurred while performing the operation",
    INCORRECT_USERNAME_PASSWORD:"Incorrect email/password",
    USER_ALREADY_EXISTS:"User with same email already exist",
    EMAIL_NOT_VERIFIED:"Email is not verified",
    TENANT_SAME_NAME_ERROR:"Tenant with name already exist",
    PROJECT_NAME_ERROR:"Project Name is mandatory",
    PROJECT_NAME_SAME_ERROR:"Project with same name already exist",
    STATUS_NAME_ERROR:"Status Name is mandatory",
    STATUS_NAME_SAME_ERROR:"Status with same name already exist",
    ID_ERROR:"ID is mandatory",
    PAGE_NO_ERROR:"Page Number is mandatory",
    PAGE_SIZE_ERROR:"Page Size is mandatory",
    ISSUE_DESCRIPTION_ERROR:"Issue Description is mandatory",
    RESET_PASSWORD_TOKEN_ERROR:"Reset Password Token Id is mandatory",
    INVALID_RESET_PASSWORD_LINK_ERROR:"Invalid or reset password link is expired",
};