module.exports = {
    EMAIL_MANDATORY_ERROR: "Email is mandatory",
    EMAIL_NOT_EXIST_ERROR: "Email is not exist or invalid email",
    PASSWORD_MANDATORY_ERROR: "Password is mandatory",
    WORKPLACE_MANDATORY_ERROR:"Work Place is manadatory",
    WORKPLACE_NOT_MATCHING_ERROR:"This User Does not exist for this Work Place",
    WORKPLACE_DOESNOT_EXISTS_ERROR:"This Work Place does not exists",
    FIRST_NAME_MANDATORY_ERROR: "FirstName is mandatory",
    LAST_NAME_MANDATORY_ERROR: "LastName is mandatory",
    TENANT_NAME_MANDATORY_ERROR: "Tenant name is mandatory",
    OTP_MANDATORY_ERROR: "OTP is mandatory",
    TENANT_ID_ERROR: "Tenant Id is mandatory",
    PROJECT_ALREADY_ERROR: "Fix version is already created for this project",
    SOME_ERROR_OCCURRED: "Some error occurred while performing the operation",
    INCORRECT_USERNAME_PASSWORD: "Incorrect Email Address/Password",
    USER_ALREADY_EXISTS: "User with same email already exist",
    EMAIL_NOT_VERIFIED: "Email is not verified",
    TENANT_SAME_NAME_ERROR: "Tenant with name already exist",
    PROJECT_NAME_ERROR: "Project Name is mandatory",
    PROJECT_NAME_SAME_ERROR: "Project with same name already exist",
    DEPARTMENT_NAME_ERROR: "Department Name is mandatory",
    DEPARTMENT_NAME_SAME_ERROR: "Department with same name already exist",
    STATUS_NAME_ERROR: "Status Name is mandatory",
    STATUS_NAME_SAME_ERROR: "Status with same name already exist",
    ID_ERROR: "ID is mandatory",
    PROJECT_ID_ERROR: "Project Id is mandatory",
    PAGE_NO_ERROR: "Page Number is mandatory",
    PAGE_SIZE_ERROR: "Page Size is mandatory",
    ISSUE_DESCRIPTION_ERROR: "Issue Description is mandatory",
    RESET_PASSWORD_TOKEN_ERROR: "Reset Password Token Id is mandatory",
    INVALID_RESET_PASSWORD_LINK_ERROR: "Invalid or reset password link is expired",
    MOBILE_MANDATORY_ERROR: "Mobile is mandatory",
    DESIGNATION_MANDATORY_ERROR: "Designation is mandatory",
    ROLE_MANDATORY_ERROR: "Role is mandatory",
    ACTIVE_MANDATORY_ERROR: "ACtive is mandatory",
    MAX_USER_ERROR: "Your current plan supports only {userCount} Users. Please upgrade your plan.",
    INACTIVE_ACCOUNT_ERROR: "Your account is Inactive. Please contact your system administrator",
    SAME_ESCALATION_ERROR: "Escalation Details for same department already exist.",
    TEAM_NAME_ERROR: "Team Name is mandatory",
    TEAM_NAME_SAME_ERROR: "Team with same name already exist",
    USERS_EMPTY_ARRAY_ERROR: "Users cannot be null",
    LEADS_EMPTY_ARRAY_ERROR: "Leads cannot be null",
    AGENT_EMPTY_ARRAY_ERROR: "Agents cannot be null",
    ASSIGNEE_NAME_ERROR: "Assignee name is mandatory",
    CATEGORY_ERROR: "Category is mandatory",
    PRIORITY_ERROR: "Priority is mandatory",
    ISSUE_DETAILS_ERROR: "Issue Details is mandatory",
    ISSUE_SUMMARY_ERROR: "Issue Summary is mandatory",
    FIELD_ERROR: "Field is mandatory",
    FILES_ERROR: "Files is mandatory",
    FIX_VERSION_ERROR: "Fix Version is mandatory",
    FIX_VERSION__ID_ERROR: "ID does not exist or Invalid ID",
    PROJECTID_ERROR_OCCURRED: "Project_id is mandatory",
    FIX_VERSION_SAME_ERROR: "Fix Version with same name already exist",
    DUE_DATE_ERROR:"Due Date is mandatory",
    STORY_POINT_ERROR:"Story Point is mandatory",
    RESOLVED_BY_ERROR:"Resolved By is mandatory",
    REVIEWED_BY_ERROR:"Reviewed By is mandatory",
    TESTED_BY_ERROR:"Tested By is mandatory",
    TICKET_ID_ERROR: "Ticket Id is mandatory",
    HTML_COMMENT_MANDATORY: "Html Comment is mandatory",
    KEY_NAME_ERROR: "KeyName is mandatory",
    FILE_DELETED_ERROR: "File is not present / might be deleted",
    FILE_DELETED: "File is deleted"
};